###################
# Parte router-nat
###################

# M칩dulo iptable_nat

- name: Cargando el m칩dulo iptable_nat...
  modprobe:
    name: iptable_nat
    state: present

- name: Haciendo iptable_nat persistente...
  lineinfile:
    path: /etc/modules
    line: iptable_nat

# Forwarding 

- name: Habilitando ipv4 forwarding (persistente)...
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes

# Iptables

- name: A침adiendo regla iptable SNAT...
  command: iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE

- name: Instalando iptables-persistent...
  apt:
    name: iptables-persistent


##########################
# Parte rutas por defecto
##########################

- name: Borrando ruta por defecto...
  command: ip route del default

- name: A침adiendo nueva ruta por defecto... 
  command: ip route add default via {{ default_route }}

- name: Haciendo la ruta por defecto persistente...
  template:
    src: interfaces-router
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: u=rw,g=r,o=r

